### ISSUE TITLE
Minimal binary sizes seem to be ... not taking everything into account

### ISSUE THREAD

**Issue by Zireael07** [c9fe/graderjs#17]
> Minimal binary is 10Mb (Windows, Hello World App). Typical Linux/MacOS binary is 14Mb (Hello World App).

> Running this will download and install Google Chrome if you don't already have it installed. 

In my experience, Google Chrome is NOT 10 or 14 mb.

**Comment by c9fe** [comment]
@Zireael07 i just feel very sad for you that you didn't see how this works
